import{a as L,S as h,i as c}from"./assets/vendor-c493984e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const w="44348563-8832aea6e55efd6ddd80494f7",v="https://pixabay.com/api/",m=async(r,e)=>{try{return(await L.get(v,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}catch(i){throw console.log(i),i}};new h(".gallery a");function u(r){return r.map(e=>`<li class="list-el">
                <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
                </div>
            </li>`).join("")}function f(){s.loader.classList.remove("hidden")}function g(){s.loader.classList.add("hidden")}function b(){s.loadMore.classList.remove("hidden")}function p(){s.loadMore.classList.add("hidden")}let n=1,d=null,y=new h(".gallery a");const s={formEl:document.querySelector(".form-el"),inputEl:document.querySelector(".input-search"),listEl:document.querySelector(".img-list"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".btn-load-more")};s.formEl.addEventListener("submit",async r=>{r.preventDefault(),s.imgGallery.innerHTML="",f(),p(),n=1,d=r.currentTarget.elements.search.value.trim();try{const e=await m(d,n);e.totalHits>0&&c.success({position:"topRight",message:`We found ${e.totalHits} photos`}),e.hits.length===0&&c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),s.imgGallery.innerHTML=u(e.hits),y.refresh(),e.totalHits>15&&b()}catch(e){console.log(e)}finally{r.target.reset(),g()}});s.loadMore.addEventListener("click",async()=>{n++,f();try{const r=await m(d,n),e=u(r.hits);s.imgGallery.insertAdjacentHTML("beforeend",e),y.refresh();const i=document.querySelector(".gallery").lastElementChild.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"});const a=Math.ceil(r.totalHits/15);n>=a&&(p(),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.log(r)}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
