import{a as f,S as p,i as l}from"./assets/vendor-ee72e1a4.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const g="44348563-8832aea6e55efd6ddd80494f7",y="https://pixabay.com/api/",L=async(t,i,a)=>{try{return(await f.get(y,{params:{key:g,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:15}})).data}catch(r){throw console.error(r),r}},w=new p(".gallery a");document.querySelector(".img-list");function v(t){const i=s.imgGallery,a=t.hits.map(r=>`<li class="list-el">
                <a href="${r.largeImageURL}"><img src='${r.webformatURL}' alt='${r.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${r.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${r.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${r.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${r.downloads}</p></div>
                </div>
            </li>`).join("");i.innerHTML=a,w.refresh()}function S(){s.loader.classList.remove("hidden")}function m(){s.loader.classList.add("hidden")}function E(){s.loadMore.classList.remove("hidden")}function h(){s.loadMore.classList.add("hidden")}let n=1,d="";const s={formEl:document.querySelector(".form-el"),inputEl:document.querySelector(".input-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".btn-load-more")};s.formEl.addEventListener("submit",async t=>{if(t.preventDefault(),s.imgGallery.innerHTML="",S(),h(),n=1,d=t.currentTarget.search.value.trim(),!d){l.error({message:"Поле пошуку повинно бути заповнене!",position:"topRight"}),m();return}await u()});s.loadMore.addEventListener("click",async()=>{n+=1,await u()});const u=async()=>{try{const t=await L(d,n);t.hits.length===0&&n===1?l.error({position:"topRight",message:"Вибачте, немає зображень, що відповідають вашому запиту. Спробуйте ще раз!"}):(v(t.hits),t.hits.length===15?E():h(),b())}catch{l.error({title:"Вибачте,",message:"Немає зображень, що відповідають вашому запиту. Спробуйте ще раз!",color:"red",position:"topRight"})}finally{m(),n===1&&s.formEl.reset()}},b=()=>{const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})};
//# sourceMappingURL=commonHelpers.js.map
